apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: my-app
type: Opaque
data:
  mysql-root-password: UjAwdCNXcFMhOXg3a0xtWg==
  mysql-user: d3B1c2Vy
  mysql-password: V3BVc3IjUEA1NSFrOHpS
