apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: my-app
type: Opaque
data:
  mysql-root-password: <base64_encoded_root_password>
  mysql-user: <base64_encoded_user>
  mysql-password: <base64_encoded_user_password>