apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wordpress-network-policy
  namespace: my-app
spec:
  podSelector:
    matchLabels:
      app: wordpress
  policyTypes:
    - Ingress
    - Egress

  # Allow incoming traffic
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: mysql
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
        - podSelector: {}

  # Allow outgoing traffic
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: mysql
    - to:
        - podSelector:
            matchLabels:
              app: wordpress
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
